// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: groupshare/messages/share.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Share_List_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Share_List_Request) Reset() {
	*x = Share_List_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupshare_messages_share_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share_List_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share_List_Request) ProtoMessage() {}

func (x *Share_List_Request) ProtoReflect() protoreflect.Message {
	mi := &file_groupshare_messages_share_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share_List_Request.ProtoReflect.Descriptor instead.
func (*Share_List_Request) Descriptor() ([]byte, []int) {
	return file_groupshare_messages_share_proto_rawDescGZIP(), []int{0}
}

type Share_List_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shares []string          `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	Names  map[string]string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Share_List_Response) Reset() {
	*x = Share_List_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupshare_messages_share_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share_List_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share_List_Response) ProtoMessage() {}

func (x *Share_List_Response) ProtoReflect() protoreflect.Message {
	mi := &file_groupshare_messages_share_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share_List_Response.ProtoReflect.Descriptor instead.
func (*Share_List_Response) Descriptor() ([]byte, []int) {
	return file_groupshare_messages_share_proto_rawDescGZIP(), []int{1}
}

func (x *Share_List_Response) GetShares() []string {
	if x != nil {
		return x.Shares
	}
	return nil
}

func (x *Share_List_Response) GetNames() map[string]string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_groupshare_messages_share_proto protoreflect.FileDescriptor

var file_groupshare_messages_share_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x5f, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xa7, 0x01, 0x0a, 0x13, 0x53, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x4c, 0x69, 0x73, 0x74,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x73, 0x12, 0x3e, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x5f, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x43, 0x5a, 0x41, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x76, 0x65, 0x2f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_groupshare_messages_share_proto_rawDescOnce sync.Once
	file_groupshare_messages_share_proto_rawDescData = file_groupshare_messages_share_proto_rawDesc
)

func file_groupshare_messages_share_proto_rawDescGZIP() []byte {
	file_groupshare_messages_share_proto_rawDescOnce.Do(func() {
		file_groupshare_messages_share_proto_rawDescData = protoimpl.X.CompressGZIP(file_groupshare_messages_share_proto_rawDescData)
	})
	return file_groupshare_messages_share_proto_rawDescData
}

var file_groupshare_messages_share_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_groupshare_messages_share_proto_goTypes = []interface{}{
	(*Share_List_Request)(nil),  // 0: messages.Share_List_Request
	(*Share_List_Response)(nil), // 1: messages.Share_List_Response
	nil,                         // 2: messages.Share_List_Response.NamesEntry
}
var file_groupshare_messages_share_proto_depIdxs = []int32{
	2, // 0: messages.Share_List_Response.names:type_name -> messages.Share_List_Response.NamesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_groupshare_messages_share_proto_init() }
func file_groupshare_messages_share_proto_init() {
	if File_groupshare_messages_share_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_groupshare_messages_share_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share_List_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupshare_messages_share_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share_List_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_groupshare_messages_share_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_groupshare_messages_share_proto_goTypes,
		DependencyIndexes: file_groupshare_messages_share_proto_depIdxs,
		MessageInfos:      file_groupshare_messages_share_proto_msgTypes,
	}.Build()
	File_groupshare_messages_share_proto = out.File
	file_groupshare_messages_share_proto_rawDesc = nil
	file_groupshare_messages_share_proto_goTypes = nil
	file_groupshare_messages_share_proto_depIdxs = nil
}
