// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: groupshare/messages/state.proto

package messages

import (
	delta "github.com/dave/protod/delta"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupshare_messages_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_groupshare_messages_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_groupshare_messages_state_proto_rawDescGZIP(), []int{0}
}

type State_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unique string    `protobuf:"bytes,1,opt,name=unique,proto3" json:"unique,omitempty"` // unique id of this request (for de-duplicate / fail / retry)
	State  int64     `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`  // state of the document that this op is acting on
	Op     *delta.Op `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`         // operation (compound if many operations)
}

func (x *State_Request) Reset() {
	*x = State_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupshare_messages_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State_Request) ProtoMessage() {}

func (x *State_Request) ProtoReflect() protoreflect.Message {
	mi := &file_groupshare_messages_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State_Request.ProtoReflect.Descriptor instead.
func (*State_Request) Descriptor() ([]byte, []int) {
	return file_groupshare_messages_state_proto_rawDescGZIP(), []int{0, 0}
}

func (x *State_Request) GetUnique() string {
	if x != nil {
		return x.Unique
	}
	return ""
}

func (x *State_Request) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *State_Request) GetOp() *delta.Op {
	if x != nil {
		return x.Op
	}
	return nil
}

type State_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unique string    `protobuf:"bytes,1,opt,name=unique,proto3" json:"unique,omitempty"` // unique id of the request (for de-duplicate / fail / retry)
	State  int64     `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`  // state of the document after the op from the client and the response op have been applied
	Op     *delta.Op `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`         // response op that must be applied to the document in order to get to the server state (compound if many operations)
}

func (x *State_Response) Reset() {
	*x = State_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupshare_messages_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State_Response) ProtoMessage() {}

func (x *State_Response) ProtoReflect() protoreflect.Message {
	mi := &file_groupshare_messages_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State_Response.ProtoReflect.Descriptor instead.
func (*State_Response) Descriptor() ([]byte, []int) {
	return file_groupshare_messages_state_proto_rawDescGZIP(), []int{0, 1}
}

func (x *State_Response) GetUnique() string {
	if x != nil {
		return x.Unique
	}
	return ""
}

func (x *State_Response) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *State_Response) GetOp() *delta.Op {
	if x != nil {
		return x.Op
	}
	return nil
}

var File_groupshare_messages_state_proto protoreflect.FileDescriptor

var file_groupshare_messages_state_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x12, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x64, 0x2f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb0, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x52, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x1a, 0x53, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x2e, 0x4f, 0x70, 0x52, 0x02,
	0x6f, 0x70, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x61, 0x76, 0x65, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x3b, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_groupshare_messages_state_proto_rawDescOnce sync.Once
	file_groupshare_messages_state_proto_rawDescData = file_groupshare_messages_state_proto_rawDesc
)

func file_groupshare_messages_state_proto_rawDescGZIP() []byte {
	file_groupshare_messages_state_proto_rawDescOnce.Do(func() {
		file_groupshare_messages_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_groupshare_messages_state_proto_rawDescData)
	})
	return file_groupshare_messages_state_proto_rawDescData
}

var file_groupshare_messages_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_groupshare_messages_state_proto_goTypes = []interface{}{
	(*State)(nil),          // 0: messages.State
	(*State_Request)(nil),  // 1: messages.State.Request
	(*State_Response)(nil), // 2: messages.State.Response
	(*delta.Op)(nil),       // 3: delta.Op
}
var file_groupshare_messages_state_proto_depIdxs = []int32{
	3, // 0: messages.State.Request.op:type_name -> delta.Op
	3, // 1: messages.State.Response.op:type_name -> delta.Op
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_groupshare_messages_state_proto_init() }
func file_groupshare_messages_state_proto_init() {
	if File_groupshare_messages_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_groupshare_messages_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupshare_messages_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupshare_messages_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_groupshare_messages_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_groupshare_messages_state_proto_goTypes,
		DependencyIndexes: file_groupshare_messages_state_proto_depIdxs,
		MessageInfos:      file_groupshare_messages_state_proto_msgTypes,
	}.Build()
	File_groupshare_messages_state_proto = out.File
	file_groupshare_messages_state_proto_rawDesc = nil
	file_groupshare_messages_state_proto_goTypes = nil
	file_groupshare_messages_state_proto_depIdxs = nil
}
