name: device
description: Dart package which manages device id.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_id: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
