name: data_repository
description: Dart package which manages data.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auth_repository:
    path: "../auth_repository"
  protod:
    path: "../../../protod"

dev_dependencies:
  flutter_test:
    sdk: flutter
