name: auth
description: Dart package which manages auth.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.1
  hive_flutter: ^0.3.0
  protobuf: ^1.0.1
  api:
    path: ../api
  device:
    path: ../device

dev_dependencies:
  flutter_test:
    sdk: flutter
