name: discovery
description: Dart package which manages service discovery.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_is_emulator_fixed: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
