// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: main/proto/share.proto

package main_proto

import (
	_ "github.com/dave/protod/google/protobuf"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Share_List_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Share_List_Request) Reset() {
	*x = Share_List_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_share_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share_List_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share_List_Request) ProtoMessage() {}

func (x *Share_List_Request) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_share_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share_List_Request.ProtoReflect.Descriptor instead.
func (*Share_List_Request) Descriptor() ([]byte, []int) {
	return file_main_proto_share_proto_rawDescGZIP(), []int{0}
}

type Share_List_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Share_List_Response_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Share_List_Response) Reset() {
	*x = Share_List_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_share_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share_List_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share_List_Response) ProtoMessage() {}

func (x *Share_List_Response) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_share_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share_List_Response.ProtoReflect.Descriptor instead.
func (*Share_List_Response) Descriptor() ([]byte, []int) {
	return file_main_proto_share_proto_rawDescGZIP(), []int{1}
}

func (x *Share_List_Response) GetItems() []*Share_List_Response_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Share_Remove_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Share_Remove_Request) Reset() {
	*x = Share_Remove_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_share_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share_Remove_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share_Remove_Request) ProtoMessage() {}

func (x *Share_Remove_Request) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_share_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share_Remove_Request.ProtoReflect.Descriptor instead.
func (*Share_Remove_Request) Descriptor() ([]byte, []int) {
	return file_main_proto_share_proto_rawDescGZIP(), []int{2}
}

func (x *Share_Remove_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Share_Delete_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Share_Delete_Request) Reset() {
	*x = Share_Delete_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_share_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share_Delete_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share_Delete_Request) ProtoMessage() {}

func (x *Share_Delete_Request) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_share_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share_Delete_Request.ProtoReflect.Descriptor instead.
func (*Share_Delete_Request) Descriptor() ([]byte, []int) {
	return file_main_proto_share_proto_rawDescGZIP(), []int{3}
}

func (x *Share_Delete_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Share_Delete_Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Share_Delete_Task) Reset() {
	*x = Share_Delete_Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_share_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share_Delete_Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share_Delete_Task) ProtoMessage() {}

func (x *Share_Delete_Task) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_share_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share_Delete_Task.ProtoReflect.Descriptor instead.
func (*Share_Delete_Task) Descriptor() ([]byte, []int) {
	return file_main_proto_share_proto_rawDescGZIP(), []int{4}
}

func (x *Share_Delete_Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Share_List_Response_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Share_List_Response_Item) Reset() {
	*x = Share_List_Response_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_proto_share_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Share_List_Response_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share_List_Response_Item) ProtoMessage() {}

func (x *Share_List_Response_Item) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_share_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share_List_Response_Item.ProtoReflect.Descriptor instead.
func (*Share_List_Response_Item) Descriptor() ([]byte, []int) {
	return file_main_proto_share_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Share_List_Response_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Share_List_Response_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_main_proto_share_proto protoreflect.FileDescriptor

var file_main_proto_share_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x22,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x61, 0x72, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x4c, 0x69, 0x73, 0x74,
	0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x77, 0x0a, 0x13, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x5f, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x4c, 0x69, 0x73, 0x74,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x2a, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x26, 0x0a, 0x14, 0x53, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x53, 0x68, 0x61,
	0x72, 0x65, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x23, 0x0a, 0x11, 0x53, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x5f, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x41, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x76, 0x65, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d, 0x61,
	0x69, 0x6e, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x8a, 0x43, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_main_proto_share_proto_rawDescOnce sync.Once
	file_main_proto_share_proto_rawDescData = file_main_proto_share_proto_rawDesc
)

func file_main_proto_share_proto_rawDescGZIP() []byte {
	file_main_proto_share_proto_rawDescOnce.Do(func() {
		file_main_proto_share_proto_rawDescData = protoimpl.X.CompressGZIP(file_main_proto_share_proto_rawDescData)
	})
	return file_main_proto_share_proto_rawDescData
}

var file_main_proto_share_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_main_proto_share_proto_goTypes = []interface{}{
	(*Share_List_Request)(nil),       // 0: main.Share_List_Request
	(*Share_List_Response)(nil),      // 1: main.Share_List_Response
	(*Share_Remove_Request)(nil),     // 2: main.Share_Remove_Request
	(*Share_Delete_Request)(nil),     // 3: main.Share_Delete_Request
	(*Share_Delete_Task)(nil),        // 4: main.Share_Delete_Task
	(*Share_List_Response_Item)(nil), // 5: main.Share_List_Response.Item
}
var file_main_proto_share_proto_depIdxs = []int32{
	5, // 0: main.Share_List_Response.items:type_name -> main.Share_List_Response.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_main_proto_share_proto_init() }
func file_main_proto_share_proto_init() {
	if File_main_proto_share_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_main_proto_share_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share_List_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_share_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share_List_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_share_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share_Remove_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_share_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share_Delete_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_share_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share_Delete_Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_proto_share_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Share_List_Response_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_main_proto_share_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_main_proto_share_proto_goTypes,
		DependencyIndexes: file_main_proto_share_proto_depIdxs,
		MessageInfos:      file_main_proto_share_proto_msgTypes,
	}.Build()
	File_main_proto_share_proto = out.File
	file_main_proto_share_proto_rawDesc = nil
	file_main_proto_share_proto_goTypes = nil
	file_main_proto_share_proto_depIdxs = nil
}
