// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: groupshare/data/snapshot.proto

package data

import (
	pserver "github.com/dave/protod/pserver"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *pserver.Snapshot `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // the snapshot
	User  string            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`   // user id
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupshare_data_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_groupshare_data_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_groupshare_data_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetValue() *pserver.Snapshot {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Snapshot) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ShareSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *pserver.Snapshot `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // the snapshot
	User  string            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`   // user id
	Name  string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`   // name of the Share
}

func (x *ShareSnapshot) Reset() {
	*x = ShareSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupshare_data_snapshot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareSnapshot) ProtoMessage() {}

func (x *ShareSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_groupshare_data_snapshot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareSnapshot.ProtoReflect.Descriptor instead.
func (*ShareSnapshot) Descriptor() ([]byte, []int) {
	return file_groupshare_data_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *ShareSnapshot) GetValue() *pserver.Snapshot {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ShareSnapshot) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ShareSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_groupshare_data_snapshot_proto protoreflect.FileDescriptor

var file_groupshare_data_snapshot_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x15, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a,
	0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x60, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x65, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x76, 0x65, 0x2f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62,
	0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x3b, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_groupshare_data_snapshot_proto_rawDescOnce sync.Once
	file_groupshare_data_snapshot_proto_rawDescData = file_groupshare_data_snapshot_proto_rawDesc
)

func file_groupshare_data_snapshot_proto_rawDescGZIP() []byte {
	file_groupshare_data_snapshot_proto_rawDescOnce.Do(func() {
		file_groupshare_data_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_groupshare_data_snapshot_proto_rawDescData)
	})
	return file_groupshare_data_snapshot_proto_rawDescData
}

var file_groupshare_data_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_groupshare_data_snapshot_proto_goTypes = []interface{}{
	(*Snapshot)(nil),         // 0: data.Snapshot
	(*ShareSnapshot)(nil),    // 1: data.ShareSnapshot
	(*pserver.Snapshot)(nil), // 2: pserver.Snapshot
}
var file_groupshare_data_snapshot_proto_depIdxs = []int32{
	2, // 0: data.Snapshot.value:type_name -> pserver.Snapshot
	2, // 1: data.ShareSnapshot.value:type_name -> pserver.Snapshot
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_groupshare_data_snapshot_proto_init() }
func file_groupshare_data_snapshot_proto_init() {
	if File_groupshare_data_snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_groupshare_data_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupshare_data_snapshot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_groupshare_data_snapshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_groupshare_data_snapshot_proto_goTypes,
		DependencyIndexes: file_groupshare_data_snapshot_proto_depIdxs,
		MessageInfos:      file_groupshare_data_snapshot_proto_msgTypes,
	}.Build()
	File_groupshare_data_snapshot_proto = out.File
	file_groupshare_data_snapshot_proto_rawDesc = nil
	file_groupshare_data_snapshot_proto_goTypes = nil
	file_groupshare_data_snapshot_proto_depIdxs = nil
}
