// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: groupshare/data/user.proto

package data

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// [proto:data]
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shares []*User_AvailableShare `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupshare_data_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_groupshare_data_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_groupshare_data_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetShares() []*User_AvailableShare {
	if x != nil {
		return x.Shares
	}
	return nil
}

type User_AvailableShare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	New  bool   `protobuf:"varint,3,opt,name=new,proto3" json:"new,omitempty"` // the new item may not be stored yet when the first list response is processed. We set this flag to prevent it being removed, and reset the flag the first time the item is returned by a list request.
}

func (x *User_AvailableShare) Reset() {
	*x = User_AvailableShare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_groupshare_data_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User_AvailableShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_AvailableShare) ProtoMessage() {}

func (x *User_AvailableShare) ProtoReflect() protoreflect.Message {
	mi := &file_groupshare_data_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_AvailableShare.ProtoReflect.Descriptor instead.
func (*User_AvailableShare) Descriptor() ([]byte, []int) {
	return file_groupshare_data_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *User_AvailableShare) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User_AvailableShare) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User_AvailableShare) GetNew() bool {
	if x != nil {
		return x.New
	}
	return false
}

var File_groupshare_data_user_proto protoreflect.FileDescriptor

var file_groupshare_data_user_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x81, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x06, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x1a, 0x46,
	0x0a, 0x0e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x03, 0x6e, 0x65, 0x77, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x76, 0x65, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x3b, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_groupshare_data_user_proto_rawDescOnce sync.Once
	file_groupshare_data_user_proto_rawDescData = file_groupshare_data_user_proto_rawDesc
)

func file_groupshare_data_user_proto_rawDescGZIP() []byte {
	file_groupshare_data_user_proto_rawDescOnce.Do(func() {
		file_groupshare_data_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_groupshare_data_user_proto_rawDescData)
	})
	return file_groupshare_data_user_proto_rawDescData
}

var file_groupshare_data_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_groupshare_data_user_proto_goTypes = []interface{}{
	(*User)(nil),                // 0: data.User
	(*User_AvailableShare)(nil), // 1: data.User.AvailableShare
}
var file_groupshare_data_user_proto_depIdxs = []int32{
	1, // 0: data.User.shares:type_name -> data.User.AvailableShare
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_groupshare_data_user_proto_init() }
func file_groupshare_data_user_proto_init() {
	if File_groupshare_data_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_groupshare_data_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_groupshare_data_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User_AvailableShare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_groupshare_data_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_groupshare_data_user_proto_goTypes,
		DependencyIndexes: file_groupshare_data_user_proto_depIdxs,
		MessageInfos:      file_groupshare_data_user_proto_msgTypes,
	}.Build()
	File_groupshare_data_user_proto = out.File
	file_groupshare_data_user_proto_rawDesc = nil
	file_groupshare_data_user_proto_goTypes = nil
	file_groupshare_data_user_proto_depIdxs = nil
}
